---
title: "2023 Summative Assessment"
author: "Lesley Mitchell (2223232)"
date: "`r Sys.Date()`"
output: 
  html_document:
    df_print: paged
    theme: 
      version: 4
      bootswatch: lux
    toc: true
    toc_float:
      collapsed: false
      smooth_scroll: false
    toc_depth: 3
    number_sections: false
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(
  echo       = FALSE,    # whether to show code chunks
  message    = FALSE,    # whether to show messages from your code
  warning    = FALSE,    # whether to show warnings from your code
  fig.width  = 8,        # figure width in inches (at 96 dpi)
  fig.height = 5,        # figure height in inches (at 96 dpi)
  fig.align  = "center", # align figures to centre of page
  out.width = "90%"      # figures/images span 90% of the page width
)

# Load libraries
library(tidyverse)
library(conflicted)   # makes conflicts between tidyverse and other packages explicit
library(kableExtra)
library(ggthemes)     # more ggplot themes
library(forcats)      # useful factor tools
library(scales)       # useful number formatting tools (e.g. adding commas, scaling, displaying currency)
library(ggrepel)      # funky positioning for geom_text to avoid overlaps
library(lemon)        # nicer facet options

# Set random seed for ggrepel (for reproducibility)
set.seed(42)

# Set plot theme
theme_set(theme_stata()) # default theme for plots

```

```{r file-import }

owid_energy <- read_csv("data/owid-energy-data.csv")

elec_access <- read_csv("data/number-of-people-with-and-without-electricity-access.csv")

iso_codes <- read_csv("data/ISO_codes.csv")

```

## Which energy source has generated the highest amount of electricity worldwide over time?

```{r highest-all-time-electricity-production }

# Averaging across time, which is the energy source (e.g. fossil fuels, nuclear power, and
# renewables) that generates the highest amount of electricity worldwide. How much
# electricity has been generated from each of these sources?

# OWID Energy Data is huge, first, trim to the useful columns:
# fossil_electricity (all of coal, oil and gas)
# nuclear_electricity
# renewables_electricity (all renewable sources, inc. solar, wind, biofuels and other)

dfTotalElectricityOverTimeBySource <- owid_energy %>%
  # Filter to world level data
  dplyr::filter(country == "World") %>%
  select(fossil_electricity, nuclear_electricity, renewables_electricity) %>%
  summarise(Fossil = sum(fossil_electricity, na.rm = TRUE),
            Nuclear = sum(nuclear_electricity, na.rm = TRUE),
            Renewables = sum(renewables_electricity, na.rm = TRUE)) %>%
  pivot_longer(everything(), names_to = "source", values_to = "production") %>%
  arrange(desc(production))

```

```{r highest-all-time-electricity-production-graph }

# For tidiness, order the columns highest to lowest value
# fct_reorder orders source by ascending values in production
# fct_rev reverses this order

ggplot(dfTotalElectricityOverTimeBySource, mapping = aes(x = fct_rev(fct_reorder(source, production)),
                                                         y = production)) +
  geom_col(fill = "lightblue") +
  labs(title = "Total electricity generated by source",
       subtitle = "(Worldwide, across all time)",
       caption = "TWh = terawatt-hours (1,000,000MWh)",
       alt = "Column graph with three columns in highest to lowest order, left to right. Largest column is for fossil fuels, middle column is for renewables, smallest column is for nuclear.") +
  xlab(NULL) +
  ylab("Total electricity produced (TWh)") +
  # Legibility fixes
  # Scale y axis values with suffix
  scale_y_continuous(labels = unit_format(unit = "K", scale = 1e-4, sep = "")) +
  # Rotate the tick values on the y axis
  theme(axis.text.y = element_text(angle = 0))

```

```{r highest-alltime-production-table }

kable(dfTotalElectricityOverTimeBySource)

```


## Primary energy consumption changed across time

```{r energy-consumption-over-time }

# How has primary energy consumption (in terawatt-hours) changed worldwide across time?
# What are the key trends?

# Useful columns
# year, primary_energy_consumption

dfPrimaryEnergyConsumption <- owid_energy %>%
  # Filter to world level data
  dplyr::filter(country == "World") %>%
  select(year, primary_energy_consumption) %>%
  # Remove all the rows with no data
  na.omit() %>%
  group_by(year) %>%
  summarise(total = sum(primary_energy_consumption)) %>%
  ungroup()

```

```{r}

ggplot(dfPrimaryEnergyConsumption, mapping = aes(x = year, y = total)) +
  geom_line() +
    labs(title = "Total primary energy consumption per year",
       subtitle = "(Worldwide)",
       caption = "TWh = terawatt-hours (1,000,000MWh)",
       alt = "Chart shows a line graph of total primary energy consumed (range: 43115.91 to 161530.75 terawatt-hours) plotted against year (range: 1965 - 2020), which generally increases from left to right, with a sharp decrease apparent in the final year.") +
  xlab(NULL) +
  ylab("Total electricity consumed (TWh)") +
  # Legibility fixes
  # Make x axis lables every 5 years between min and max values
  scale_x_continuous(breaks = seq(min(dfPrimaryEnergyConsumption$year), max(dfPrimaryEnergyConsumption$year),5)) +
  # Scale y axis values with suffix and increase number of breaks
  scale_y_continuous(labels = unit_format(unit = "K", scale = 1e-4, sep = ""),
                     n.breaks = 8) +
  # Rotate the tick values on the y axis
  theme(axis.text.y = element_text(angle = 0))

```

## Consumption per continent (1970 - 2020) from specific sources

```{r consumption-per-continent-specific-sources }

# Focussing on human energy consumption from specific sources (i.e. coal, oil, gas, nuclear,
# hydropower, solar, wind, and biofuel). How much energy has been consumed per continent
# for each year between 1970 and 2020? Comment on the trends you observe.

dfPerContinentPerSource <- owid_energy %>%
  # filter for rows where year between 1970 and 2020
  dplyr::filter(between(year,1970, 2020)) %>%
  # Merge continents data with owid_energy data
  left_join(iso_codes, by = c("iso_code" = "ISO_Code")) %>%
  rename(continent = Continent) %>%
  # Select useful columns
  select(continent, year, coal_consumption, oil_consumption, gas_consumption,
         nuclear_consumption, hydro_consumption, solar_consumption,
         wind_consumption, biofuel_consumption) %>%
  # filter for rows where continent is NA
  dplyr::filter(!is.na(continent)) %>%
  # replace all the NA data with 0 or the sum fails!!
  replace(is.na(.), 0) %>%
  group_by(continent, year) %>%
  # Summarise all the consumption columns
  summarise(across(where(is.numeric), sum)) %>%
  ungroup() %>%
  # Make the data longer
  pivot_longer(cols = ends_with("n"), names_to = "sources", values_to = "total") %>%
  # Factor and rename the sources data, convert the continents data to an ordered factor
  mutate(sources = fct_recode(sources, "Coal" = "coal_consumption", "Oil" = "oil_consumption",
                              "Gas" = "gas_consumption", "Nuclear" = "nuclear_consumption",
                              "Hydro" = "hydro_consumption", "Solar" = "solar_consumption",
                              "Wind" ="wind_consumption", "Biofuel" = "biofuel_consumption"),
         continent = fct_relevel(continent, "Africa", "Asia", "Europe", "North America",
                                 "South America", "Oceania"))

```

```{r consumption-per-continent-specific-sources-graphs, fig.height=15}

ggplot(dfPerContinentPerSource, mapping = aes(x = year, y = total)) +
  geom_line(aes(color = fct_reorder2(sources, year, total))) +
  facet_rep_wrap(vars(continent), ncol = 1, scales = "free_y",
                 # Because this is a long set of graphs, add the year ticks to each one
                 repeat.tick.labels = 'bottom') +
  labs(title = "Consumption of electricity produced from specific sources",
       subtitle = "By continent (1970 - 2020)",
       caption = "1 TWh = 1,000,000 MWh") +
  xlab(NULL) +
  ylab("Total electricity consumed (TWh)") +
  # Legibility fixes
  # Rather than a legend label the lines (using the same colours as the lines)
  geom_text_repel(aes(label = sources, color = fct_reorder2(sources, year, total)),
                  data = subset(dfPerContinentPerSource, year == 1970),
                  hjust = "right", nudge_x = -3, direction = "y",
                  size = 3) +
  # Make x axis labels every 2 years between min and max values in the data
  scale_x_continuous(breaks = seq(min(dfPerContinentPerSource$year),
                                  max(dfPerContinentPerSource$year), 2)) +
  # Scale y axis using a square root transform, to make small values more visible
  # Format labels with commas
  scale_y_sqrt(labels = comma) +
  # Rotate the tick values on the x and y axes, and make the text a smidge smaller
  theme(axis.text.y = element_text(angle = 0, size = 8),
        axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1, size = 8),
        # Add the x axis grid lines back (stata theme doesn't use them)
        panel.grid.major.x = element_line(),
        # Remove the legend (since the lines are labelled)
        legend.position = "none") +
  # Apply a colourblind friendly colour set
  scale_color_viridis_d(option = "H")

```

## Electricity access for different income levels

```{r electricity-access-income }
# What is the percentage of people with/ without electricity access for different income
# categories? Comment on the trends for each year between 1990 and 2019, and focus on
# income categories labelled High income, Upper middle income, Lower middle income, and
# Low income.

# Discussion of data here: https://ourworldindata.org/energy-access
# World Bank defined income levels change each year (adjusted for inflation) and countries included do too
# Based on Gross National Income (GNI) per capita
# e.g. for 2020-2021 - 
#   https://blogs.worldbank.org/opendata/new-world-bank-country-classifications-income-level-2020-2021
# Historical classification spreadsheet here - 
#   https://datacatalogfiles.worldbank.org/ddh-published/0037712/DR0090754/OGHIST.xlsx

dfElectricityAccessIncome <- elec_access %>%
  select(!Code) %>%
  dplyr::filter(Entity %in% c("High income", "Upper middle income", "Lower middle income", "Low income") &
                  between(Year, 1990, 2019)) %>%
  rename("income_level" = "Entity", "year" = "Year",
         "with_access" = "Number of people with access to electricity",
         "without_access" = "Number of people without access to electricity") %>%
  # Summarise across years as percentage
  group_by(income_level, year) %>%
  mutate(pct_with = round(100 * with_access / sum(with_access, without_access), digits = 2),
         pct_without = round(100 * without_access / sum(with_access, without_access), digits = 2)) %>%
  ungroup() %>%
  # Make income_levels an ordered factor and add some formatting
  mutate(income_level = fct_recode(income_level, "High\nincome" = "High income",
                                   "Upper\n middle\nincome" = "Upper middle income",
                                   "Lower\n middle\nincome" = "Lower middle income",
                                   "Low\nincome" = "Low income"))


```

```{r electricity-access-income-chart }

ggplot(dfElectricityAccessIncome, mapping = aes(x = year, y = pct_without, label = pct_without)) +
  geom_line(aes(color = income_level)) +
  geom_point(aes(color = income_level)) +
  labs(title = "Percentage population without electricity access",
       subtitle = "By World Bank Income Level (1990 - 2019)",
       caption = "Value for high income countries declines from 0.12% to 0 across the time period") +
  xlab(NULL) +
  ylab("percent") +
  # Legibility fixes
  # Add values to each point
  geom_text_repel(data = subset(dfElectricityAccessIncome, pct_without > 0.5),
                  hjust = "left",
                  direction = "both",
                  size = 2) +
  # Rather than a legend label the lines (using the same colours as the lines)
  geom_text_repel(data = subset(dfElectricityAccessIncome, year == 2019),
                  aes(label = income_level, color = income_level),
                  hjust = "right",
                  nudge_x = 4,
                  direction = "y",
                  size = 3) +
  # Make x axis labels every 1 year between min and max values in the data
  scale_x_continuous(breaks = seq(min(dfElectricityAccessIncome$year),
                                  max(dfElectricityAccessIncome$year), 1)) +
  # Format labels with commas
  scale_y_sqrt(labels = comma) +
  # Rotate the tick values on the x and y axes, and make the text a smidge smaller
  theme(axis.text.y = element_text(angle = 0, size = 8),
        axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1, size = 8),
        # Remove the legend (since the lines are labelled)
        legend.position = "none") +
  # Apply a colourblind friendly colour set
  scale_color_viridis_d(option = "H") +
  scale_fill_viridis_d(option = "H")

```

